# Generated by Django 3.1 on 2020-10-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20201030_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invest',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
