# Generated by Django 3.1 on 2020-10-31 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(default='other', max_length=255),
        ),
    ]
