# Generated by Django 3.1 on 2020-11-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='invest',
            name='ts',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
