# Generated by Django 3.1 on 2020-11-06 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_invest_ts'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('name', 'category')},
        ),
    ]
